### ISSUE TITLE
Empty Output

### ISSUE THREAD

**Issue by Silv3rHorn** [woanware/autorunner#1]
Hi,

I obtained an empty output when I tried running the latest release (v0.0.14) against the recent Magnet User Summit 2019 CTF image.

Steps Taken:
1) Mount image as writable on *G:\\* with Arsenal Image Mounter
2) Start autorunner as Administrator
3) Point registry path to *G:\Windows\system32\config\\*
4) Point catalogue path to *G:\Windows\system32\CatRoot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\\*
5) Add a mapping of *C:\\* to *G:\\* and checked *Is Windows Drive*

Other Steps Attempted (with the same outcome):
1) Using FTK Imager to mount
2) Extracting Registry Hives to a folder while preserving original directory structure
3) Extracting Registry Hives to a folder without preserving original directory structure
4) Point catalogue path to *G:\Windows\system32\CatRoot\\*
5) Tried other forensic images such as cfreds

May I know what I have done incorrectly?

Regards.

**Comment by woanware** [comment]
I use it by extracting the registry hives, catroot files out of the
forensic image to your local drive first

**Comment by Silv3rHorn** [comment]
Hm, I tried this and wasn't able to get it to work. May I know if the extracted files preserve the original directory structure, and is autorunner able to scan a folder recursively for hives and catalog files?

**Comment by woanware** [comment]
Yes it will recurse through the directories

**Comment by woanware** [comment]
Is the image you used publicly available or can it be shared?

**Comment by Silv3rHorn** [comment]
Its available here: https://www.hecfblog.com/2019/04/daily-blog-657-mus2019-dfir-ctf-open-to.html


I have also attached the [Errors.txt](https://github.com/woanware/autorunner/files/3173013/Errors.txt) generated by autorunner.

**Comment by woanware** [comment]
Can you delete the error log, and rerun with the v0.0.15 release. It won't fix the issue but it might give me more visibility.

I have tested against that image, and it works OK here

**Comment by woanware** [comment]
Scrub that. I did some more research and debugging. Turns out if your local time is offset from UTC by any value, then it causes a DateTimeOffset error when initialising to a minimum value. I set my local time to UTC+1, and I got the same error. I have changed the code, retested and it now works....

So if you can test v0.0.16, which should hopefully work now!

**Comment by Silv3rHorn** [comment]
With v0.0.16 and using the test image, there is output now. Thanks for the assistance!
